#!/bin/sh

export MISSKEY_GEN_URLS_PRIMARY=http://misskey.local:5001
export MISSKEY_GEN_URLS_SECONDARY=http://misskey-uc.local:5003
export MISSKEY_GEN_TLS_ENABLE=0
export MISSKEY_GEN_TLS_KEY=
export MISSKEY_GEN_TLS_CERT=
export MISSKEY_GEN_MONGO_HOST=db
export MISSKEY_GEN_MONGO_AUTH=0
export MISSKEY_GEN_MONGO_USER=
export MISSKEY_GEN_MONGO_PASSWORD=
export MISSKEY_GEN_REDIS_HOST=redis
export MISSKEY_GEN_REDIS_AUTH=0
export MISSKEY_GEN_REDIS_PASSWORD=
export MISSKEY_GEN_PORTS_API=5000
export MISSKEY_GEN_PORTS_WEB_HTTP=5001
export MISSKEY_GEN_PORTS_WEB_HTTPS=
export MISSKEY_GEN_PORTS_FILE_INTERNAL=5002
export MISSKEY_GEN_PORTS_FILE_HTTP=5003
export MISSKEY_GEN_PORTS_FILE_HTTPS=
export MISSKEY_GEN_RECAPTCHA_SITE="6LfttG0UAAAAAI5Gm3qLNeXntMJkb9a-ATLj6REJ"
export MISSKEY_GEN_RECAPTCHA_SECRET="6LfttG0UAAAAABszaA04EqjIqp7zcplAGrjnHGrg"
export MISSKEY_GEN_THEME_COLOR="#4b7559"
export MISSKEY_GEN_FILE_STORAGE_PATH=/app/storage

docker run -it --rm \
    -v "$(pwd)/deps/misskey-gen:/app" \
    -v "$(pwd)/conf:/app/store" \
    -w /app \
    -e "MISSKEY_GEN_URLS_PRIMARY=$MISSKEY_GEN_URLS_PRIMARY" \
    -e "MISSKEY_GEN_URLS_SECONDARY=$MISSKEY_GEN_URLS_SECONDARY" \
    -e "MISSKEY_GEN_URLS_SECONDARY=$MISSKEY_GEN_URLS_SECONDARY" \
    -e "MISSKEY_GEN_TLS_ENABLE=$MISSKEY_GEN_TLS_ENABLE" \
    -e "MISSKEY_GEN_TLS_KEY=$MISSKEY_GEN_TLS_KEY" \
    -e "MISSKEY_GEN_TLS_CERT=$MISSKEY_GEN_TLS_CERT" \
    -e "MISSKEY_GEN_MONGO_HOST=$MISSKEY_GEN_MONGO_HOST" \
    -e "MISSKEY_GEN_MONGO_AUTH=$MISSKEY_GEN_MONGO_AUTH" \
    -e "MISSKEY_GEN_MONGO_USER=$MISSKEY_GEN_MONGO_USER" \
    -e "MISSKEY_GEN_MONGO_PASSWORD=$MISSKEY_GEN_MONGO_PASSWORD" \
    -e "MISSKEY_GEN_REDIS_HOST=$MISSKEY_GEN_REDIS_HOST" \
    -e "MISSKEY_GEN_REDIS_AUTH=$MISSKEY_GEN_REDIS_AUTH" \
    -e "MISSKEY_GEN_REDIS_PASSWORD=$MISSKEY_GEN_REDIS_PASSWORD" \
    -e "MISSKEY_GEN_PORTS_API=$MISSKEY_GEN_PORTS_API" \
    -e "MISSKEY_GEN_PORTS_WEB_HTTP=$MISSKEY_GEN_PORTS_WEB_HTTP" \
    -e "MISSKEY_GEN_PORTS_WEB_HTTPS=$MISSKEY_GEN_PORTS_WEB_HTTPS" \
    -e "MISSKEY_GEN_PORTS_FILE_INTERNAL=$MISSKEY_GEN_PORTS_FILE_INTERNAL" \
    -e "MISSKEY_GEN_PORTS_FILE_HTTP=$MISSKEY_GEN_PORTS_FILE_HTTP" \
    -e "MISSKEY_GEN_PORTS_FILE_HTTPS=$MISSKEY_GEN_PORTS_FILE_HTTPS" \
    -e "MISSKEY_GEN_RECAPTCHA_SITE=$MISSKEY_GEN_RECAPTCHA_SITE" \
    -e "MISSKEY_GEN_RECAPTCHA_SECRET=$MISSKEY_GEN_RECAPTCHA_SECRET" \
    -e "MISSKEY_GEN_THEME_COLOR=$MISSKEY_GEN_THEME_COLOR" \
    -e "MISSKEY_GEN_FILE_STORAGE_PATH=$MISSKEY_GEN_FILE_STORAGE_PATH" \
    --entrypoint "sh" \
    node:8-alpine \
    -c "npm install && npm start"
